TriathlonTrainingsWebApp/Controllers/GeneralTrainingOverwiewController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using TriathlonTrainingsWebApp.Models;

namespace TriathlonTrainingsWebApp.Controllers
{
    [Authorize]
    public class GeneralTrainingOverwiewController : Controller
    {
        private TriathlonContext db = new TriathlonContext();

       
        public async Task<ActionResult> TrainingOverwiew(TriathlonTraining triathlonTraining)
        {
          
            return View(await db.TriathlonActivities.ToListAsync());
        }
        public async Task<ActionResult> TrainingOverwiew7Days(TriathlonTraining triathlonTraining)
        {

            return View(await db.TriathlonActivities.ToListAsync());
        }
        public async Task<ActionResult> TrainingOverwiew30Days(TriathlonTraining triathlonTraining)
        {

            return View(await db.TriathlonActivities.ToListAsync());
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TriathlonTrainingsWebApp/Controllers/MyCompetitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TriathlonTrainingsWebApp.Models;

namespace TriathlonTrainingsWebApp.Controllers
{
    public class MyCompetitionsController : Controller
    {
        private TriathlonContext db = new TriathlonContext();

        // GET: MyCompetitions
        public async Task<ActionResult> Competitions(MyCompetition myCompetition)
        {
            //myCompetition.Date = myCompetition.Date.Date;
            
            return View(await db.MyCompetitions.ToListAsync());
        }
       
        // GET: MyCompetitions/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: MyCompetitions/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Date,Distance,Description,DaysLeft")] MyCompetition myCompetition)
        {
            if (ModelState.IsValid)
            {
                db.MyCompetitions.Add(myCompetition);
                await db.SaveChangesAsync();
                return RedirectToAction("Competitions");
            }

            return View(myCompetition);
        }

        // GET: MyCompetitions/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyCompetition myCompetition = await db.MyCompetitions.FindAsync(id);
            if (myCompetition == null)
            {
                return HttpNotFound();
            }
            return View(myCompetition);
        }

        // POST: MyCompetitions/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Date,Distance,Description,Link,DaysLeft")] MyCompetition myCompetition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(myCompetition).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Competitions");
            }
            return View(myCompetition);
        }

        // GET: MyCompetitions/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyCompetition myCompetition = await db.MyCompetitions.FindAsync(id);
            if (myCompetition == null)
            {
                return HttpNotFound();
            }
            return View(myCompetition);
        }

        // POST: MyCompetitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            MyCompetition myCompetition = await db.MyCompetitions.FindAsync(id);
            db.MyCompetitions.Remove(myCompetition);
            await db.SaveChangesAsync();
            return RedirectToAction("Competitions");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TriathlonTrainingsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color:black; color:white">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trainings overwiew", "TrainingOverwiew", "GeneralTrainingOverwiew")</li>
                    <li>@Html.ActionLink("Trainings list", "AllTrainingsList", "TriathlonTrainings")</li>
                    <li>@Html.ActionLink("Add new training", "Create", "TriathlonTrainings")</li>
                    <li>@Html.ActionLink("My competitions", "Competitions", "MyCompetitions")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - my application ASP.NET</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>